/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project.View;
import java.sql.*;
import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Muliani
 */
public class EditBarangFrame extends javax.swing.JFrame {
    static BarangPanel brg;
    
    /**
     * Creates new form EditBarangFrame
     */
    public EditBarangFrame() {
        initComponents();
        ltBasementComboBox.setVisible(false);
    }

    EditBarangFrame(BarangPanel aThis) {
        this.brg = aThis;
        initComponents();
        ltBasementComboBox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tanggalTextField = new javax.swing.JTextField();
        jumlahTextField = new javax.swing.JTextField();
        lantaiComboBox = new javax.swing.JComboBox<>();
        ltSatuComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ltBasementComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        warningLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cariTextField = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        statusComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Edit Barang");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/stuff.png"))); // NOI18N

        updateButton.setBackground(new java.awt.Color(204, 255, 255));
        updateButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 0, 102));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        kembaliButton.setBackground(new java.awt.Color(204, 255, 255));
        kembaliButton.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        kembaliButton.setForeground(new java.awt.Color(0, 0, 102));
        kembaliButton.setText("kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Nama : ");

        namaTextField.setBackground(new java.awt.Color(102, 0, 102));
        namaTextField.setFont(new java.awt.Font("OCR-A BT", 0, 12)); // NOI18N
        namaTextField.setForeground(new java.awt.Color(255, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Tempat :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Tanggal :");

        tanggalTextField.setBackground(new java.awt.Color(102, 0, 102));
        tanggalTextField.setFont(new java.awt.Font("OCR-A BT", 0, 12)); // NOI18N
        tanggalTextField.setForeground(new java.awt.Color(255, 204, 255));

        jumlahTextField.setBackground(new java.awt.Color(102, 0, 102));
        jumlahTextField.setFont(new java.awt.Font("OCR-A BT", 0, 12)); // NOI18N
        jumlahTextField.setForeground(new java.awt.Color(255, 204, 255));

        lantaiComboBox.setBackground(new java.awt.Color(102, 0, 102));
        lantaiComboBox.setFont(new java.awt.Font("OCR-A BT", 0, 12)); // NOI18N
        lantaiComboBox.setForeground(new java.awt.Color(255, 204, 255));
        lantaiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "Basement" }));
        lantaiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lantaiComboBoxActionPerformed(evt);
            }
        });

        ltSatuComboBox.setBackground(new java.awt.Color(102, 0, 102));
        ltSatuComboBox.setFont(new java.awt.Font("OCR-A BT", 0, 12)); // NOI18N
        ltSatuComboBox.setForeground(new java.awt.Color(255, 204, 255));
        ltSatuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auditorium" }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("lantai :");

        ltBasementComboBox.setBackground(new java.awt.Color(102, 0, 102));
        ltBasementComboBox.setFont(new java.awt.Font("OCR-A BT", 0, 12)); // NOI18N
        ltBasementComboBox.setForeground(new java.awt.Color(255, 204, 255));
        ltBasementComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unit Kesenian" }));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Lokasi :");

        warningLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("ID :");

        cariTextField.setBackground(new java.awt.Color(102, 0, 102));
        cariTextField.setFont(new java.awt.Font("OCR-A BT", 0, 12)); // NOI18N
        cariTextField.setForeground(new java.awt.Color(255, 204, 255));

        cariButton.setBackground(new java.awt.Color(255, 255, 153));
        cariButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cariButton.setForeground(new java.awt.Color(102, 102, 0));
        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        statusComboBox.setBackground(new java.awt.Color(102, 0, 102));
        statusComboBox.setFont(new java.awt.Font("OCR-A BT", 0, 12)); // NOI18N
        statusComboBox.setForeground(new java.awt.Color(255, 204, 255));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PSM", "OSM" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Kepemilikan :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kembaliButton)
                                        .addGap(99, 99, 99)
                                        .addComponent(updateButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tanggalTextField)
                                            .addComponent(jumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(cariButton)
                            .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(17, 17, 17)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ltSatuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(namaTextField)
                                            .addComponent(lantaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(ltBasementComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lantaiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltSatuComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ltBasementComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cariButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tanggalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jumlahTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kembaliButton)
                    .addComponent(updateButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean validasi(){
        String nama = namaTextField.getText();
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        if("".equals(nama)){
            warningLabel.setText("Nama tidak boleh kosong");
            return false;
        } else if (tanggalTextField.getText() == ""){
            warningLabel.setText("Tanggal tidak boleh kosong");
            return false;
        } else if (jumlahTextField.getText() == ""){
            warningLabel.setText("Jumlah tidak boleh kosong");
            return false;
        } 
        try {
            LocalDate.parse(tanggalTextField.getText(), dateFormatter);
        } catch (Exception e) {
            warningLabel.setText("masukkan format tanggal yang benar(yyyy-MM-dd)");
            return false;
        }
        try{
            int jumlah = Integer.parseInt(jumlahTextField.getText());
            if(jumlah <= 0){
                warningLabel.setText("Jumlah harus lebih dari 0");
                return false;
            }
        } catch (Exception e){
            warningLabel.setText("Jumlah harus dalam bentuk angka!");
            return false;
        }
        return true;
    }
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if(validasi()){
            String lokasi = null;
            switch((String) lantaiComboBox.getSelectedItem()){
                        case "1":
                        lokasi = (String) ltSatuComboBox.getSelectedItem();
                        break;
                        case "Basement":
                        lokasi = (String) ltBasementComboBox.getSelectedItem();
                        break;
                    }
            String tempat = "Lantai " + (String) lantaiComboBox.getSelectedItem() + ", " + lokasi;
            Barang barang = new Barang();
            DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            barang.setTanggal(tanggalTextField.getText());
            barang.setNama(namaTextField.getText());
            barang.setTempat(tempat);
            barang.setJumlah(Integer.parseInt(jumlahTextField.getText()));
            barang.setID(cariTextField.getText());
            barang.setStatus((String) statusComboBox.getSelectedItem());
            try {
                if(Database.getInstance().editBarang(barang)){
                    JOptionPane.showMessageDialog(null,"Barang sudah berhasil diubah!");
                                this.brg.loadTableData();
                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(null,"Barang gagal diubah!");
                                this.brg.loadTableData();
                            }
            } catch (SQLException ex) {
                Logger.getLogger(EditBarangFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void lantaiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lantaiComboBoxActionPerformed
        // TODO add your handling code here:
        switch(lantaiComboBox.getSelectedIndex()){
            case 0 :
            ltSatuComboBox.setVisible(true);
            ltBasementComboBox.setVisible(false);
            break;
            case 1:
            ltBasementComboBox.setVisible(true);
            ltSatuComboBox.setVisible(false);
            break;
        }
    }//GEN-LAST:event_lantaiComboBoxActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        // TODO add your handling code here:
        
        try {
            Barang barang = Database.getInstance().cariBarang(cariTextField.getText());
            if((barang.getTempat()==null)){
                namaTextField.setText(barang.getNama());
                tanggalTextField.setText(String.valueOf(barang.getTanggal()));
                jumlahTextField.setText(String.valueOf(barang.getJumlah()));
            } else{
                JOptionPane.showMessageDialog(null,barang.getTempat());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cariButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField cariTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jumlahTextField;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JComboBox<String> lantaiComboBox;
    private javax.swing.JComboBox<String> ltBasementComboBox;
    private javax.swing.JComboBox<String> ltSatuComboBox;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField tanggalTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
