/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project.View;

import javax.swing.JOptionPane;

/**
 *
 * @author Muliani
 */
public class MainFrame extends javax.swing.JFrame {
    private String type = null;
    static LoginFrame login;
    static RegisterFrame register;
    /**
     * Creates new form MainFrame
     */
    
    public MainFrame(LoginFrame login,String type) {
        this.login = login;
        this.type = type;
        if("user, diterima".equalsIgnoreCase(this.type)){
            initComponents();
            akunButton.setVisible(false);
            contentScrollPane.setViewportView(new HomePanel());
        } else if("user, belum diterima".equalsIgnoreCase(this.type)){
            JOptionPane.showMessageDialog(this,"Anda belum diterima! Silahkan hubungi admin");
            WelcomeFrame welcome = new WelcomeFrame();
            welcome.setVisible(true);
            this.dispose();
        } else if("admin, diterima".equalsIgnoreCase(this.type) || "admin, belum diterima".equalsIgnoreCase(this.type)){
            initComponents();
            contentScrollPane.setViewportView(new HomePanel());
        }
    }
    
    public MainFrame(RegisterFrame register) {
        JOptionPane.showMessageDialog(this,"Anda belum diterima! Silahkan hubungi admin");
        WelcomeFrame welcome = new WelcomeFrame();
        welcome.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        contentScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        barangButton = new javax.swing.JButton();
        akunButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentScrollPane.setBackground(new java.awt.Color(204, 255, 204));
        jSplitPane2.setRightComponent(contentScrollPane);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        homeButton.setBackground(new java.awt.Color(204, 255, 255));
        homeButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        homeButton.setForeground(new java.awt.Color(0, 0, 102));
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        barangButton.setBackground(new java.awt.Color(204, 255, 255));
        barangButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        barangButton.setForeground(new java.awt.Color(0, 0, 102));
        barangButton.setText("Barang");
        barangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangButtonActionPerformed(evt);
            }
        });

        akunButton.setBackground(new java.awt.Color(204, 255, 255));
        akunButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        akunButton.setForeground(new java.awt.Color(0, 0, 102));
        akunButton.setText("Akun");
        akunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunButtonActionPerformed(evt);
            }
        });

        printButton.setBackground(new java.awt.Color(0, 102, 102));
        printButton.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        printButton.setForeground(new java.awt.Color(102, 255, 102));
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(akunButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barangButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(akunButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(printButton)
                .addContainerGap())
        );

        jSplitPane2.setLeftComponent(jPanel1);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setForeground(new java.awt.Color(102, 51, 0));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jMenu3.setBackground(new java.awt.Color(51, 255, 204));
        jMenu3.setForeground(new java.awt.Color(102, 51, 0));
        jMenu3.setText("Akun");

        logoutMenuItem.setBackground(new java.awt.Color(0, 255, 204));
        logoutMenuItem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        logoutMenuItem.setForeground(new java.awt.Color(0, 102, 0));
        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(logoutMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        this.type =null;
        WelcomeFrame welcome = new WelcomeFrame();
        welcome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new HomePanel());
    }//GEN-LAST:event_homeButtonActionPerformed

    private void barangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new BarangPanel());
    }//GEN-LAST:event_barangButtonActionPerformed

    private void akunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunButtonActionPerformed
        // TODO add your handling code here:
        contentScrollPane.setViewportView(new AkunPanel());
    }//GEN-LAST:event_akunButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        PrintPanel printPanel = new PrintPanel(this.login, this.type);
        contentScrollPane.setViewportView(printPanel);
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akunButton;
    private javax.swing.JButton barangButton;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables
}
