/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Project.View;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.util.List;


/**
 *
 * @author Muliani
 */
public class PrintPanel extends javax.swing.JPanel {
    private String type = null;
    static LoginFrame login;
    static RegisterFrame register;
    static Cetak cetak;

    /**
     * Creates new form MainFrame
     */
    public PrintPanel(LoginFrame login, String type) {
        this.login = login;
        this.type = type;
        
        // Initialize components first
        initComponents();
        
        // Set visibility of pakunButton based on user type
        if ("user, diterima".equalsIgnoreCase(this.type)) {
            pakunButton.setVisible(false);
        } else if ("user, belum diterima".equalsIgnoreCase(this.type)) {
            JOptionPane.showMessageDialog(this, "Anda belum diterima! Silahkan hubungi admin");
            WelcomeFrame welcome = new WelcomeFrame();
            welcome.setVisible(true);
        } else if ("admin, diterima".equalsIgnoreCase(this.type) || "admin, belum diterima".equalsIgnoreCase(this.type)) {
            // admin is allowed to see the pakunButton
            pakunButton.setVisible(true);
        }
        
         // Inisialisasi objek cetak
        cetak = new Cetak();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pbarangButton = new javax.swing.JButton();
        pakunButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/print.png"))); // NOI18N

        pbarangButton.setBackground(new java.awt.Color(102, 0, 204));
        pbarangButton.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        pbarangButton.setForeground(new java.awt.Color(255, 255, 204));
        pbarangButton.setText("Print Tabel Barang");
        pbarangButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pbarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbarangButtonActionPerformed(evt);
            }
        });

        pakunButton.setBackground(new java.awt.Color(102, 0, 204));
        pakunButton.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        pakunButton.setForeground(new java.awt.Color(255, 255, 204));
        pakunButton.setText("Print Tabel Akun");
        pakunButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pakunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pakunButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pakunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pbarangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbarangButton)
                .addGap(18, 18, 18)
                .addComponent(pakunButton)
                .addGap(0, 41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pbarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbarangButtonActionPerformed
        // TODO add your handling code here:
            try {
            List<Barang> barangList = Database.getInstance().getListBarang();
            cetak.exportTableToCSV("barang", "barang.csv");
            //printBarangTable(barangList);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error fetching barang data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pbarangButtonActionPerformed

    private void pakunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pakunButtonActionPerformed
        // TODO add your handling code here:
         try {
            cetak.exportTableToCSV("users", "akun.csv");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error exporting data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pakunButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pakunButton;
    private javax.swing.JButton pbarangButton;
    // End of variables declaration//GEN-END:variables
}
